/*
 * Directory-v3
 * Welcome on the documentation for the Directory v3 API. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: developers@lucca.fr
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.UserApplicationDataProfileFiggo;
import com.konfigthis.client.model.UserApplicationDataProfileUtime;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for UserApplicationData
 */
public class UserApplicationDataTest {
    private final UserApplicationData model = new UserApplicationData();

    /**
     * Model tests for UserApplicationData
     */
    @Test
    public void testUserApplicationData() {
        // TODO: test UserApplicationData
    }

    /**
     * Test the property 'profileFiggo'
     */
    @Test
    public void profileFiggoTest() {
        // TODO: test profileFiggo
    }

    /**
     * Test the property 'profileUtime'
     */
    @Test
    public void profileUtimeTest() {
        // TODO: test profileUtime
    }

}
