/*
 * Directory-v3
 * Welcome on the documentation for the Directory v3 API. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: developers@lucca.fr
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.ModelNull;
import com.konfigthis.client.model.UsersListExcludedFormerResponseItemsInnerCalendar;
import com.konfigthis.client.model.UsersListExcludedFormerResponseItemsInnerCulture;
import com.konfigthis.client.model.UsersListExcludedFormerResponseItemsInnerPicture;
import com.konfigthis.client.model.UsersListExcludedFormerResponseItemsInnerUserWorkCyclesInner;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for UsersListExcludedFormerResponseItemsInner
 */
public class UsersListExcludedFormerResponseItemsInnerTest {
    private final UsersListExcludedFormerResponseItemsInner model = new UsersListExcludedFormerResponseItemsInner();

    /**
     * Model tests for UsersListExcludedFormerResponseItemsInner
     */
    @Test
    public void testUsersListExcludedFormerResponseItemsInner() {
        // TODO: test UsersListExcludedFormerResponseItemsInner
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'url'
     */
    @Test
    public void urlTest() {
        // TODO: test url
    }

    /**
     * Test the property 'displayName'
     */
    @Test
    public void displayNameTest() {
        // TODO: test displayName
    }

    /**
     * Test the property 'modifiedOn'
     */
    @Test
    public void modifiedOnTest() {
        // TODO: test modifiedOn
    }

    /**
     * Test the property 'lastName'
     */
    @Test
    public void lastNameTest() {
        // TODO: test lastName
    }

    /**
     * Test the property 'firstName'
     */
    @Test
    public void firstNameTest() {
        // TODO: test firstName
    }

    /**
     * Test the property 'login'
     */
    @Test
    public void loginTest() {
        // TODO: test login
    }

    /**
     * Test the property 'mail'
     */
    @Test
    public void mailTest() {
        // TODO: test mail
    }

    /**
     * Test the property 'dtContractStart'
     */
    @Test
    public void dtContractStartTest() {
        // TODO: test dtContractStart
    }

    /**
     * Test the property 'dtContractEnd'
     */
    @Test
    public void dtContractEndTest() {
        // TODO: test dtContractEnd
    }

    /**
     * Test the property 'birthDate'
     */
    @Test
    public void birthDateTest() {
        // TODO: test birthDate
    }

    /**
     * Test the property 'employeeNumber'
     */
    @Test
    public void employeeNumberTest() {
        // TODO: test employeeNumber
    }

    /**
     * Test the property 'calendar'
     */
    @Test
    public void calendarTest() {
        // TODO: test calendar
    }

    /**
     * Test the property 'culture'
     */
    @Test
    public void cultureTest() {
        // TODO: test culture
    }

    /**
     * Test the property 'picture'
     */
    @Test
    public void pictureTest() {
        // TODO: test picture
    }

    /**
     * Test the property 'applicationData'
     */
    @Test
    public void applicationDataTest() {
        // TODO: test applicationData
    }

    /**
     * Test the property 'legalEntity'
     */
    @Test
    public void legalEntityTest() {
        // TODO: test legalEntity
    }

    /**
     * Test the property 'department'
     */
    @Test
    public void departmentTest() {
        // TODO: test department
    }

    /**
     * Test the property 'manager'
     */
    @Test
    public void managerTest() {
        // TODO: test manager
    }

    /**
     * Test the property 'rolePrincipal'
     */
    @Test
    public void rolePrincipalTest() {
        // TODO: test rolePrincipal
    }

    /**
     * Test the property 'habilitedRoles'
     */
    @Test
    public void habilitedRolesTest() {
        // TODO: test habilitedRoles
    }

    /**
     * Test the property 'userWorkCycles'
     */
    @Test
    public void userWorkCyclesTest() {
        // TODO: test userWorkCycles
    }

}
