/*
 * Directory-v3
 * Welcome on the documentation for the Directory v3 API. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: developers@lucca.fr
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.ModelNull;
import com.konfigthis.client.model.UsersUpdateByIdRequestHabilitedRolesInner;
import com.konfigthis.client.model.UsersUpdateByIdRequestUserWorkCyclesInner;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for UsersCreateNewUserResponse
 */
public class UsersCreateNewUserResponseTest {
    private final UsersCreateNewUserResponse model = new UsersCreateNewUserResponse();

    /**
     * Model tests for UsersCreateNewUserResponse
     */
    @Test
    public void testUsersCreateNewUserResponse() {
        // TODO: test UsersCreateNewUserResponse
    }

    /**
     * Test the property 'firstName'
     */
    @Test
    public void firstNameTest() {
        // TODO: test firstName
    }

    /**
     * Test the property 'lastName'
     */
    @Test
    public void lastNameTest() {
        // TODO: test lastName
    }

    /**
     * Test the property 'mail'
     */
    @Test
    public void mailTest() {
        // TODO: test mail
    }

    /**
     * Test the property 'login'
     */
    @Test
    public void loginTest() {
        // TODO: test login
    }

    /**
     * Test the property 'legalEntityId'
     */
    @Test
    public void legalEntityIdTest() {
        // TODO: test legalEntityId
    }

    /**
     * Test the property 'dtContractStart'
     */
    @Test
    public void dtContractStartTest() {
        // TODO: test dtContractStart
    }

    /**
     * Test the property 'dtContractEnd'
     */
    @Test
    public void dtContractEndTest() {
        // TODO: test dtContractEnd
    }

    /**
     * Test the property 'cspId'
     */
    @Test
    public void cspIdTest() {
        // TODO: test cspId
    }

    /**
     * Test the property 'calendarId'
     */
    @Test
    public void calendarIdTest() {
        // TODO: test calendarId
    }

    /**
     * Test the property 'employeeNumber'
     */
    @Test
    public void employeeNumberTest() {
        // TODO: test employeeNumber
    }

    /**
     * Test the property 'birthDate'
     */
    @Test
    public void birthDateTest() {
        // TODO: test birthDate
    }

    /**
     * Test the property 'userWorkCycles'
     */
    @Test
    public void userWorkCyclesTest() {
        // TODO: test userWorkCycles
    }

    /**
     * Test the property 'departmentId'
     */
    @Test
    public void departmentIdTest() {
        // TODO: test departmentId
    }

    /**
     * Test the property 'managerId'
     */
    @Test
    public void managerIdTest() {
        // TODO: test managerId
    }

    /**
     * Test the property 'rolePrincipalId'
     */
    @Test
    public void rolePrincipalIdTest() {
        // TODO: test rolePrincipalId
    }

    /**
     * Test the property 'habilitedRoles'
     */
    @Test
    public void habilitedRolesTest() {
        // TODO: test habilitedRoles
    }

    /**
     * Test the property 'cultureId'
     */
    @Test
    public void cultureIdTest() {
        // TODO: test cultureId
    }

    /**
     * Test the property 'address'
     */
    @Test
    public void addressTest() {
        // TODO: test address
    }

    /**
     * Test the property 'bankName'
     */
    @Test
    public void bankNameTest() {
        // TODO: test bankName
    }

    /**
     * Test the property 'directLine'
     */
    @Test
    public void directLineTest() {
        // TODO: test directLine
    }

    /**
     * Test the property 'jobTitle'
     */
    @Test
    public void jobTitleTest() {
        // TODO: test jobTitle
    }

    /**
     * Test the property 'gender'
     */
    @Test
    public void genderTest() {
        // TODO: test gender
    }

    /**
     * Test the property 'nationality'
     */
    @Test
    public void nationalityTest() {
        // TODO: test nationality
    }

    /**
     * Test the property 'personalEmail'
     */
    @Test
    public void personalEmailTest() {
        // TODO: test personalEmail
    }

    /**
     * Test the property 'personalMobile'
     */
    @Test
    public void personalMobileTest() {
        // TODO: test personalMobile
    }

    /**
     * Test the property 'professionalMobile'
     */
    @Test
    public void professionalMobileTest() {
        // TODO: test professionalMobile
    }

    /**
     * Test the property 'quote'
     */
    @Test
    public void quoteTest() {
        // TODO: test quote
    }

}
